name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
    - name: install phosg  
      run: git clone https://github.com/neonzhang/phosg.git
      run: sudu apt-get install cmake
      run: sudo apt-get install g++
run: sudo apt-get install Python
run: cd phosg
run: make
run: sudo make install
run: cd ../
run: sudo apt-get install libevent-dev
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
