name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
#    - name: configure
#      run: ./configure
run: git clone https://github.com/neonzhang/newserv.git
     cd newserv
     git clone https://github.com/neonzhang/phosg.git
    sudu apt-get install cmake
    sudo apt-get install g++
    sudo apt-get install Python
    cd phosg
    sudo make
    sudo make install
    cd ../
    sudo apt-get install libevent-dev
    make
    make check
    make distcheck
